# Experiment 5
## Build a Neural Network model to predict whether tumor is malignant or benign for Breast Cancer Winconsin(Diagnostic) using Python.

## Using Inbuilt dataset
Here we are using Inbuilt dataset for model
## MLP Classifier
The `MLPClassifier` is a multi-layer perceptron classifier used for classification tasks in machine learning. It employs neural network layers, activation functions, and optimization techniques to learn and predict class labels based on input data. It's customizable through hyperparameters and is trained on labeled datasets to make predictions.

In [1]:
# For making dataframe
import pandas as pd
# For dataset
from sklearn.datasets import load_breast_cancer
# For splitting between training and testing data
from sklearn.model_selection import train_test_split
# Importing neural network
from sklearn.neural_network import MLPClassifier
# For checking accuracy
from sklearn.metrics import accuracy_score

# Loading the dataset
cancer_data = load_breast_cancer()

# Converting to dataframe
data_df = pd.DataFrame(data = cancer_data.data,
					columns = cancer_data.feature_names)

print("Dataset in Dataframe is:\n")
print(data_df.head().T)

Dataset in Dataframe is:

                                   0            1            2           3  \
mean radius                17.990000    20.570000    19.690000   11.420000   
mean texture               10.380000    17.770000    21.250000   20.380000   
mean perimeter            122.800000   132.900000   130.000000   77.580000   
mean area                1001.000000  1326.000000  1203.000000  386.100000   
mean smoothness             0.118400     0.084740     0.109600    0.142500   
mean compactness            0.277600     0.078640     0.159900    0.283900   
mean concavity              0.300100     0.086900     0.197400    0.241400   
mean concave points         0.147100     0.070170     0.127900    0.105200   
mean symmetry               0.241900     0.181200     0.206900    0.259700   
mean fractal dimension      0.078710     0.056670     0.059990    0.097440   
radius error                1.095000     0.543500     0.745600    0.495600   
texture error               0.905300  

In [3]:
# Splitting between Input and Output
X,Y = cancer_data['data'], cancer_data['target']
print("Input is:\n",X,"\n\nOutput is:\n",Y)
print("\nShape of Input is:",X.shape,"\nShape of Output is:",Y.shape)

Input is:
 [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] 

Output is:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1

In [9]:
# Spliting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=42)

# Create a neural network classifier
clf = MLPClassifier(hidden_layer_sizes=(30, 30, 30), max_iter=1000)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Predict the labels of the test data
y_pred = clf.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of Neural Network is: {accuracy * 100:.2f}%')

Accuracy of Neural Network is: 94.15%


## Using UCI dataset
Here we are using UCI dataset for model
## Keras Model
`keras.Sequential` is a fundamental component in Keras, a deep learning library. It creates a linear stack of neural network layers for building models. Layers are added sequentially, and data flows from one to the next. It's widely used for building various types of neural networks, including feedforward and convolutional models.

In [10]:
# Import necessary libraries
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
# For normalizing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Import the dataset from an online resource
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"

column_names = ["ID", "Diagnosis", "Mean Radius", "Mean Texture", "Mean Perimeter", "Mean Area", "Mean Smoothness",
                "Mean Compactness", "Mean Concavity", "Mean Concave Points", "Mean Symmetry", "Mean Fractal Dimension",
                "SE Radius", "SE Texture", "SE Perimeter", "SE Area", "SE Smoothness", "SE Compactness", "SE Concavity",
                "SE Concave Points", "SE Symmetry", "SE Fractal Dimension", "Worst Radius", "Worst Texture",
                "Worst Perimeter", "Worst Area", "Worst Smoothness", "Worst Compactness", "Worst Concavity",
                "Worst Concave Points", "Worst Symmetry", "Worst Fractal Dimension"]
data = pd.read_csv(url, header=None, names=column_names)

# Drop the ID column as it's not useful for classification
data = data.drop(columns=["ID"])

# Convert the 'Diagnosis' column to binary labels (Malignant = 1, Benign = 0)
data['Diagnosis'] = data['Diagnosis'].map({'M': 1, 'B': 0})

# Split the data into features (X) and labels (y)
X = data.drop(columns=["Diagnosis"])
y = data["Diagnosis"]

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build a neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(30,)),  # Input layer with 30 features
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer with sigmoid activation for binary classification
])

## Description of the code
This code defines a neural network model for binary classification using TensorFlow's Keras API. Here's a breakdown of the model:

1. **Input Layer**: This layer specifies the input shape with 30 features, corresponding to the number of columns in your dataset.

2. **Hidden Layers**: The model has two hidden layers. The first hidden layer has 64 neurons with a ReLU (Rectified Linear Unit) activation function, and the second hidden layer has 32 neurons with a ReLU activation function. These layers are responsible for learning and capturing patterns in the data.

3. **Output Layer**: The output layer has a single neuron with a sigmoid activation function. Sigmoid is commonly used for binary classification tasks because it squashes the output between 0 and 1, making it suitable for predicting probabilities. A value close to 1 indicates a prediction of "Malignant," while a value close to 0 indicates "Benign."

So, this is a feedforward neural network with an input layer, two hidden layers, and an output layer designed for binary classification, specifically for classifying breast cancer diagnoses as either malignant (1) or benign (0).

In [ ]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
12/12 [==============================] - 3s 31ms/step - loss: 0.5422 - accuracy: 0.7198 - val_loss: 0.3759 - val_accuracy: 0.8791
Epoch 2/50
12/12 [==============================] - 0s 13ms/step - loss: 0.2857 - accuracy: 0.9203 - val_loss: 0.2364 - val_accuracy: 0.9560
Epoch 3/50
12/12 [==============================] - 0s 10ms/step - loss: 0.1778 - accuracy: 0.9643 - val_loss: 0.1735 - val_accuracy: 0.9560
Epoch 4/50
12/12 [==============================] - 0s 11ms/step - loss: 0.1290 - accuracy: 0.9780 - val_loss: 0.1400 - val_accuracy: 0.9670
Epoch 5/50
12/12 [==============================] - 0s 8ms/step - loss: 0.1014 - accuracy: 0.9835 - val_loss: 0.1214 - val_accuracy: 0.9670
Epoch 6/50
12/12 [==============================] - 0s 7ms/step - loss: 0.0852 - accuracy: 0.9808 - val_loss: 0.1109 - val_accuracy: 0.9670
Epoch 7/50
12/12 [==============================] - 0s 8ms/step - loss: 0.0747 - accuracy: 0.9835 - val_loss: 0.1033 - val_accuracy: 0.9560
Epoch 8/50
12/12

## Description of the code
In this code, the neural network model is compiled and trained using TensorFlow and Keras. Here's what each part of the code does:

1. **Compiling the Model**:
   - `model.compile(...)`: This step configures the training process of the model.
   - `optimizer='adam'`: It specifies the optimization algorithm to use. "Adam" is a popular optimizer known for its efficiency in training deep neural networks.
   - `loss='binary_crossentropy'`: This sets the loss function. In binary classification problems, "binary_crossentropy" is commonly used as the loss function.
   - `metrics=['accuracy']`: This specifies the evaluation metric to monitor during training, which is accuracy in this case. It helps assess how well the model is performing.

2. **Training the Model**:
   - `model.fit(...)`: This function trains the neural network on the training data.
   - `X_train` and `y_train` are the input features and labels for training.
   - `epochs=50`: It defines the number of times the entire training dataset is passed forward and backward through the neural network during training (in this case, 50 epochs).
   - `batch_size=32`: It specifies the number of training examples used in each update of the model's weights. Smaller batch sizes can lead to more accurate updates but can be slower.
   - `validation_split=0.2`: This splits a portion (20%) of the training data for validation during training. It helps monitor the model's performance on data it hasn't seen during training to detect overfitting.

The `history` object returned by `model.fit` contains information about the training process, including training and validation loss and accuracy for each epoch. We can use this information to visualize and analyze how well the model is learning from the data.

In [11]:
# Evaluate the model on the test set
y_pred = (model.predict(X_test) > 0.5).astype("int32")
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy of the Neural Network is: {accuracy * 100}")
print(f"\nConfusion Matrix:\n{conf_matrix}")
print(f"\nClassification Report:\n{class_report}")

4/4 [==============================] - 0s 4ms/step
Accuracy of the Neural Network is: 58.77192982456141

Confusion Matrix:
[[32 39]
 [ 8 35]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.45      0.58        71
           1       0.47      0.81      0.60        43

    accuracy                           0.59       114
   macro avg       0.64      0.63      0.59       114
weighted avg       0.68      0.59      0.58       114

