# Experiment 4
## Implement classification rules process on dataset using Naive Bayes algorithm.

## Naive Bayes Classifier

- **Bayesian Probability**: Naive Bayes is based on Bayes' theorem, which calculates the probability of an event based on prior knowledge and relevant evidence.

 - Bayes' theorem is used to calculate the conditional probability of an event (A) given prior knowledge of another related event (B). The formula is expressed as:

  - ` P(A|B) = (P(B|A) * P(A)) / P(B)`

  Where:
  - \(P(A|B)\) is the conditional probability of event A given event B.
  - \(P(B|A)\) is the conditional probability of event B given event A.
  - \(P(A)\) is the prior probability of event A.
  - \(P(B)\) is the prior probability of event B.

 In the context of Naive Bayes classification, \(P(A|B)\) represents the probability of a particular class (A) given a set of observed features (B), and it's calculated using prior probabilities and likelihoods as explained in the previous response.

- **Naive Assumption**: It assumes feature independence, meaning that each feature is considered independent of others. This simplifies calculations, making it "naive."

- **Training Phase**:
  - **Data Collection**: Collect a labeled dataset with features and corresponding class labels.
  - **Prior Probabilities**: Calculate prior probabilities of each class (the probability that an instance belongs to each class).
  - **Likelihood Estimation**: Estimate the likelihood of each feature given each class (conditional probabilities).
  - **Class Priors**: Calculate class priors based on the frequency of each class in the dataset.

- **Prediction Phase**:
  - **Input Features**: Given a new instance with features, calculate the likelihood of each feature for each class.
  - **Posterior Probabilities**: Use Bayes' theorem to calculate the posterior probabilities for each class based on the prior probabilities, class priors, and likelihoods.
  - **Classification**: Assign the class with the highest posterior probability as the predicted class.

- **Smoothing** (Optional):
  - To handle cases where a feature doesn't appear in the training data for a particular class, smoothing techniques like Laplace smoothing can be applied to avoid zero probabilities.

- **Applications**: Naive Bayes is commonly used in text classification (e.g., spam detection and sentiment analysis) and other classification tasks.

- **Strengths**:
  - Simple and computationally efficient.
  - Can handle high-dimensional data.
  - Often works well for text data.

- **Limitations**:
  - The independence assumption might not hold in some real-world scenarios.
  - Can be sensitive to irrelevant features.
  - May not perform well when classes are highly imbalanced.

- **Variants**: There are different variants of Naive Bayes, such as Multinomial Naive Bayes for text data and Gaussian Naive Bayes for continuous data.

- **Real-Life Example**: In spam email classification, Naive Bayes calculates the probability that an email is spam or not based on the likelihood of certain words or phrases appearing in spam or non-spam emails.

In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix

# Load the Iris dataset
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a Naive Bayes classifier (Gaussian Naive Bayes)
classifier = GaussianNB()

# Train the classifier on the training data
classifier.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = classifier.predict(X_test)

# Evaluate the classifier's performance
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, target_names=iris.target_names)

# Print the results
print("Confusion Matrix:\n", confusion_mat)
print("\nClassification Report:\n", classification_rep)

Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      0.92      0.96        13
   virginica       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

